-- CreateEnum
CREATE TYPE "RequestKind" AS ENUM ('RESIDENT_REQUEST', 'VENDOR_INQUIRY', 'SALES_SPAM', 'OTHER_NON_REQUEST');

-- AlterTable
ALTER TABLE "Request" ADD COLUMN     "kind" "RequestKind" NOT NULL DEFAULT 'RESIDENT_REQUEST';
